
pvp:
  pattern: "In law, an overruling sentence is a statement that nullifies a previous case decision as a precedent. </s> <TEXT> </s> Question: Is this sentence overruling? Answer: <mask>."
  verbalizer:
    "not overruling": 'No'
    "overruling": 'Yes'
    
adapter:
  model: "microsoft/deberta-v2-xxlarge" 
  arch: lora
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: True
  