
pvp:
  pattern: "<TEXT> </s> Question: What is the category of this institution? Answer: <mask>."
  verbalizer:
    "company": 'Company'
    "research institute": 'Institute'
    "university": 'University'
    
adapter:
  model: "microsoft/deberta-v2-xxlarge" 
  arch: lora
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: True
  