
pvp:
  pattern: "<TEXT> </s> Question: Should this paper be included in a meta-review which includes the findings of systematic reviews on interventions designed to promote charitable donations? Answer: <mask>."
  verbalizer:
    "not included": 'No'
    "included": 'Yes'
    
adapter:
  model: "microsoft/deberta-v2-xxlarge" 
  arch: lora
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: True
  