
pvp:
  pattern: "Transformative AI (TAI) is defined as AI that precipitates a transition comparable to (or more significant than) the agricultural or industrial revolution </s> <TEXT> </s> Question: Is this paper a TAI safety research paper? Answer: <mask>."
  verbalizer:
    "not TAI safety research": 'No'
    "TAI safety research": 'Yes'
    
adapter:
  model: "microsoft/deberta-v2-xxlarge" 
  arch: lora
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: True
  