
dataset:
  data: yahoo
  pattern:
    prompt: "<mask> Question: <TEXT>"
    qa: "<TEXT> </s> Question: What is the topic of this question? Answer: <mask>."
  verbalizer:
    0: "Society"
    1: "Science"
    2: "Health"
    3: "Education"
    4: "Computer"
    5: "Sports"
    6: "Business"
    7: "Entertainment"
    8: "Relationship"
    9: "Politics"
    
adapter:
  model:
    roberta-large: "roberta-large"
    roberta: "roberta-base" 
  arch:
    - lora
    - ia3
    - pfeiffer
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: False
  