# The data_path contains folders, which in turn contain test and train files (csv).
# The run_script will run experiments for all of these folders

dataset:
  data_path: ../ukpsam-annotation/datasets/petapter/september/
  out_path: results/september_data # if False, the results are saved in the data_path
  ## pattern dictionary with pattern name and pattern string. name is used for result folder creation
  pattern:
    prompt: "The stance of this paragraph regarding weapons delivery to ukraine is <mask>: <TEXT>"
  verbalizer:
    FOR: "pro"
    AGAINST: "con"
    "NO": "none"

adapter:
  model:
    xlmroberta: "xlm-roberta-large"
  arch: pfeiffer
  c_rate: 16 # can also be a list, then a subfolder for each value is created for each experiment
  learning_rate: 5e-5
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: True

