
dataset:
  data: ukraine
  pattern:
    "prompt": "This sentence contains <mask> arms deliveries to Ukraine: <TEXT>"
    "no": "<mask>: <TEXT>"
  verbalizer:
    "argumentagainst": 'a'
    "argumentfor": 'b'
    "claimagainst": 'c'
    "claimfor": 'd'
    "nostance": 'e'
    
adapter:
  model:
    xlmroberta-alpha: "xlm-roberta-large"
  arch: lora
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: False
  