
dataset:
  data: ukraine
  pattern:
    "prompt": "This sentence contains <mask> <mask> arms deliveries to Ukraine: <TEXT>"
  verbalizer:
    "argumentagainst": 'argument against'
    "argumentfor": 'argument for'
    "claimagainst": 'claim against'
    "claimfor": 'claim for'
    "nostance": 'nothing regarding'
    
adapter:
  model:
    xlmroberta-full10: "xlm-roberta-large"
  arch: full
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 10
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: False
  