
dataset:
  data: yelp
  pattern:
    prompt: "<TEXT> </s> All in all, it was <mask>."
    qa: "<TEXT> </s> Question: What does the customer think of this restaurant? Answer: <mask>."
  verbalizer:
    0: "terrible"
    1: "bad"
    2: "okay"
    3: "good"
    4: "great"
    
adapter:
  model:
    roberta-large: "roberta-large"
    roberta: "roberta-base"
  arch:
    - lora
    - ia3
    - pfeiffer
  c_rate: 16
  r: 8
  alpha: 16
  learning_rate: 5.0e-5
  max_epochs: 30
  number_of_runs: 5
  per_device_train_batch_size: 2
  save: False
  